version: 1.0.{build}
skip_tags: true
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
before_build:
- ps: >-
    Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion

    nuget restore
build:
  project: SilverlightUnitTestAdapter.sln
  verbosity: quiet
after_build:
- cmd: nuget pack .\SilverlightUnitTestAdapter.Plugin\SilverlightUnitTestAdapter.Plugin.nuspec -Prop version=%APPVEYOR_BUILD_VERSION% -Prop configuration=%CONFIGURATION%
artifacts:
- path: .\Installer\bin\**\*.vsix
  name: VSIX
- path: SilverlightUnitTestAdapter.Plugin.*.nupkg
  name: NuGet Package