version: 1.0.{build}
skip_tags: true
configuration: Release
platform: Any CPU
init:
- ps: >-
    # Microsoft Silverlight 5 Toolkit (December 2011)

    $msiFilePath = "$($env:USERPROFILE)\Silverlight_5_Toolkit_December_2011.1.msi"

    $logFilePath = "$($env:TEMP)\Silverlight_5_Toolkit_December_2011.1.txt"

    $webclient = New-Object System.Net.WebClient

    $webclient.DownloadFile('https://github.com/MicrosoftArchive/SilverlightToolkit/releases/download/5/Silverlight_5_Toolkit_December_2011.1.msi', $msiFilePath)

    $process = (Start-Process -FilePath "msiexec.exe" -ArgumentList "/i $msiFilePath /quiet /l*v $logFilePath" -Wait -Passthru)

    $exitCode = $process.ExitCode

    if ($exitCode -ne 0)

    {
      Get-Content $logFilePath
      throw "Command failed with exit code $exitCode."
    }

    del $msiFilePath

    del $logFilePath

    Write-Host "Microsoft Silverlight 5 Toolkit (December 2011) successfully installed" -ForegroundColor Green
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
nuget:
  disable_publish_on_pr: true
before_build:
- ps: >-
    Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion

    nuget restore
build:
  project: SilverlightUnitTestAdapter.sln
  verbosity: quiet
artifacts:
- path: .\Installer\bin\**\*.vsix
  name: VSIX